// Unlike locales.js, this file only cares about what the user has set as
// their Facebook language, of which there are 110. Below are all the
// "Sponsored" translations in each language.

export const sponsoredTranslations = {
  "af_ZA": "Geborg",
  "am_ET": "የተከፈለበት ማስታወቂያ",
  "ar_AR": "إعلان مُموَّل",
  "as_IN": "পৃষ্ঠপোষকতা কৰা",
  "az_AZ": "Sponsor dəstəkli",
  "be_BY": "Рэклама",
  "bg_BG": "Спонсорирано",
  "bn_IN": "সৌজন্যে",
  "br_FR": "Paeroniet",
  "bs_BA": "Sponzorirano",
  "ca_ES": "Patrocinat",
  "cb_IQ": "پاڵپشتیکراو",
  "co_FR": "Spunsurizatu",
  "cs_CZ": "Sponzorováno",
  "cx_PH": "Giisponsoran",
  "cy_GB": "Noddwyd",
  "da_DK": "Sponsoreret",
  "de_DE": "Gesponsert",
  "el_GR": "Χορηγούμενη",
  "en_GB": "Sponsored",
  "en_PI": "Chartered",
  "en_UD": "pəɹosuodS",
  "en_US": "Sponsored",
  "eo_EO": "Reklamo",
  "es_ES": "Publicidad",
  "es_LA": "Publicidad",
  "et_EE": "Sponsitud",
  "eu_ES": "Babestua",
  "fa_IR": "دارای پشتیبانی مالی",
  "ff_NG": "Yoɓanaama",
  "fi_FI": "Sponsoroitu",
  "fo_FO": "Stuðlað",
  "fr_CA": "Commandité",
  "fr_FR": "Sponsorisé",
  "fy_NL": "Sponsore",
  "ga_IE": "Urraithe",
  "gl_ES": "Patrocinado",
  "gn_PY": "Oñepatrosinapyre",
  "gu_IN": "પ્રાયોજિત",
  "ha_NG": "Daukar Nauyi",
  "he_IL": "ממומן",
  "hi_IN": "प्रायोजित",
  "hr_HR": "Plaćeni oglas",
  "ht_HT": "Peye",
  "hu_HU": "Hirdetés",
  "hy_AM": "Գովազդային",
  "id_ID": "Bersponsor",
  "is_IS": "Kostað",
  "it_IT": "Sponsorizzata",
  "ja_JP": "広告",
  "ja_KS": "広告",
  "jv_ID": "Disponsori",
  "ka_GE": "რეკლამა",
  "kk_KZ": "Демеушілік көрсеткен",
  "km_KH": "បានឧបត្ថម្ភ",
  "kn_IN": "ಪ್ರಾಯೋಜಿತ",
  "ko_KR": "", // no translation in Korean yet, I guess
  "ku_TR": "Sponsorkirî",
  "ky_KG": "Демөөрчүлөнгөн",
  "lo_LA": "ໄດ້ຮັບການສະໜັບສະໜູນ",
  "lt_LT": "Remiama",
  "lv_LV": "Apmaksāta", // cuts off reklāma as part of the thing that gets rid of the U.S. disclaimer
  "mg_MG": "Misy mpanohana",
  "mk_MK": "Спонзорирано",
  "ml_IN": "സ്പോൺസർ ചെയ്തത്",
  "mn_MN": "Ивээн тэтгэсэн",
  "mr_IN": "प्रायोजित",
  "ms_MY": "Ditaja",
  "mt_MT": "Sponsorjat",
  "my_MM": "ပံ့ပိုးထားသည်",
  "nb_NO": "Sponset",
  "ne_NP": "प्रायोजित",
  "nl_BE": "Gesponsord",
  "nl_NL": "Gesponsord",
  "nn_NO": "Sponsa",
  "or_IN": "ପ୍ରଯୋଜିତ",
  "pa_IN": "ਸਰਪ੍ਰਸਤੀ ਪ੍ਰਾਪਤ",
  "pl_PL": "Sponsorowane",
  "ps_AF": "تمويل شوي",
  "pt_BR": "Patrocinado",
  "pt_PT": "Patrocinado",
  "ro_RO": "Sponsorizat",
  "ru_RU": "Реклама",
  "rw_RW": "Icyamamaza ndasukirwaho",
  "sc_IT": "Patronadu de:",
  "si_LK": "අනුග්‍රහය දක්වන ලද",
  "sk_SK": "Sponzorované",
  "sl_SI": "Sponzorirano",
  "sn_ZW": "Zvabhadharirwa",
  "so_SO": "La maalgeliyey",
  "sq_AL": "Sponsorizuar",
  "sr_RS": "Спонзорисано",
  "sv_SE": "Sponsrad",
  "sw_KE": "Imedhaminiwa",
  "sy_SY": "", // I only get broken Unicode characters for this one
  "sz_PL": "Szpōnzorowane",
  "ta_IN": "விளம்பரம்",
  "te_IN": "స్పాన్సర్ చేసినవి",
  "tg_TJ": "Бо сарпарастӣ",
  "th_TH": "ได้รับการสนับสนุน",
  "tl_PH": "May Sponsor",
  "tr_TR": "Sponsorlu",
  "tt_RU": "Хәйрияче",
  "uk_UA": "Реклама",
  "ur_PK": "تعاون کردہ",
  "uz_UZ": "Reklama",
  "vi_VN": "Được tài trợ",
  "zh_CN": "赞助内容",
  "zh_HK": "贊助",
  "zh_TW": "贊助",
  "zz_TR": "Sponsorıdû"
};
