// Unlike locales.js, this file only cares about what the user has set as
// their Facebook language, of which there are 143, last I counted. Below
// are all the "Sponsored" translations in each language. Some languages are
// clearly a work-in-progress as the text is still mostly English, e.g. iu_CA

export const sponsoredTranslations = {
  "af_ZA": "Geborg",
  "ak_GH": "",
  "am_ET": "የተከፈለበት ማስታወቂያ",
  "ar_AR": "مُموَّل",
  "as_IN": "পৃষ্ঠপোষকতা কৰা",
  "ay_BO": "",
  "az_AZ": "Sponsor dəstəkli",
  "be_BY": "Рэклама",
  "bg_BG": "Спонсорирано",
  "bn_IN": "সৌজন্যে",
  "bp_IN": "",
  "br_FR": "Paeroniet",
  "bs_BA": "Sponzorirano",
  "bv_DE": "",
  "ca_ES": "Patrocinat",
  "cb_IQ": "پاڵپشتیکراو",
  "ck_US": "ᎤᎵᏍᎪᎸᏛᎢ",
  "co_FR": "Spunsurizatu",
  "cs_CZ": "Sponzorováno",
  "cx_PH": "Giisponsoran",
  "cy_GB": "Noddwyd",
  "da_DK": "Sponsoreret",
  "de_DE": "Gesponsert",
  "el_GR": "Χορηγούμενη",
  "em_ZM": "",
  "en_GB": "Sponsored",
  "en_PI": "Chartered",
  "en_UD": "pəɹosuodS",
  "en_US": "Sponsored",
  "eo_EO": "Reklamo",
  "es_ES": "Publicidad",
  "es_LA": "Publicidad",
  "et_EE": "Sponsitud",
  "eu_ES": "Babestua",
  "fa_IR": "دارای پشتیبانی مالی",
  "fb_LT": "5p4m",
  "ff_NG": "Yoɓanaama",
  "fi_FI": "Sponsoroitu",
  "fo_FO": "Stuðlað",
  "fr_CA": "Commandité",
  "fr_FR": "Sponsorisé",
  "fy_NL": "Sponsore",
  "ga_IE": "Urraithe",
  "gl_ES": "Patrocinado",
  "gn_PY": "Oñepatrosinapyre",
  "gu_IN": "પ્રાયોજિત",
  "gx_GR": "Χορηγούμενον",
  "ha_NG": "Daukar Nauyi",
  "he_IL": "ממומן",
  "hi_IN": "प्रायोजित",
  "hr_HR": "Plaćeni oglas",
  "ht_HT": "Peye",
  "hu_HU": "Hirdetés",
  "hy_AM": "Գովազդային",
  "id_ID": "Bersponsor",
  "ig_NG": "",
  "ik_US": "Akiḷiiŋaruat sutigun",
  "is_IS": "Kostað",
  "it_IT": "Sponsorizzato",
  "iu_CA": "",
  "ja_JP": "広告",
  "ja_KS": "広告",
  "jv_ID": "Disponsori",
  "ka_GE": "რეკლამა",
  "kk_KZ": "Демеушілік көрсеткен",
  "km_KH": "បានឧបត្ថម្ភ",
  "kn_IN": "ಪ್ರಾಯೋಜಿತ",
  "ko_KR": "",
  "ks_IN": "",
  "ku_TR": "Sponsorkirî",
  "ky_KG": "Демөөрчүлөнгөн",
  "la_VA": "Expensum",
  "lg_UG": "Kisasuliddwa",
  "li_NL": "geld in gestooke",
  "ln_CD": "Efutami",
  "lo_LA": "ຜູ້ສະໜັບສະໜູນ",
  "lt_LT": "Remiama",
  "lv_LV": "Apmaksāta reklāma",
  "mg_MG": "Misy Mpiantoka",
  "mi_NZ": "",
  "mk_MK": "Спонзорирано",
  "ml_IN": "സ്പോൺസർ ചെയ്തത്",
  "mn_MN": "Ивээн тэтгэсэн",
  "mr_IN": "प्रायोजित",
  "ms_MY": "Ditaja",
  "mt_MT": "Sponsorjat",
  "my_MM": "ပံ့ပိုးထားသည်",
  "nb_NO": "Sponset",
  "nd_ZW": "kusekelwe",
  "ne_NP": "प्रायोजित",
  "nl_BE": "Gesponsord",
  "nl_NL": "Gesponsord",
  "nn_NO": "Sponsa",
  "nr_ZA": "",
  "ns_ZA": "",
  "ny_MW": "Zamalonda",
  "om_ET": "Deeggarameera",
  "or_IN": "ପ୍ରଯୋଜିତ",
  "pa_IN": "ਸਰਪ੍ਰਸਤੀ ਪ੍ਰਾਪਤ",
  "pl_PL": "Sponsorowane",
  "ps_AF": "تمويل شوي",
  "pt_BR": "Patrocinado",
  "pt_PT": "Patrocinado",
  "qb_DE": "",
  "qc_GT": "",
  "qe_US": "",
  "qk_DZ": "Tettunefk-as tedrimt",
  "qr_GR": "",
  "qs_DE": "",
  "qt_US": "",
  "qu_PE": "",
  "qv_IT": "",
  "ro_RO": "Sponsorizat",
  "ru_RU": "Реклама",
  "rw_RW": "Icyamamaza ndasukirwaho",
  "sc_IT": "Patronadu de:",
  "si_LK": "අනුග්‍රාහක",
  "sk_SK": "Sponzorované",
  "sl_SI": "Sponzorirano",
  "sn_ZW": "Zvabhadharirwa",
  "so_SO": "La maalgeliyey",
  "sq_AL": "Sponsorizuar",
  "sr_RS": "Спонзорисано",
  "sv_SE": "Sponsrad",
  "sw_KE": "Imedhaminiwa",
  "sy_SY": "",
  "sz_PL": "Szpōnzorowane",
  "ta_IN": "விளம்பரம்",
  "te_IN": "ప్రాయోజితం చేయబడింది",
  "tg_TJ": "Бо сарпарастӣ",
  "th_TH": "ได้รับการสนับสนุน",
  "tl_PH": "May Sponsor",
  "tr_TR": "Sponsorlu",
  "tt_RU": "Хәйрияче",
  "tz_MA": "",
  "uk_UA": "Реклама",
  "ur_PK": "تعاون کردہ",
  "uz_UZ": "Reklama",
  "vi_VN": "Được tài trợ",
  "zh_CN": "赞助内容",
  "zh_HK": "贊助",
  "zh_TW": "贊助",
  "zz_TR": "Sponsorıdû",
};
